### ISSUE TITLE
Update memory adress ?

### ISSUE THREAD

**Issue by m0k1** [zeelorenc/fcnpc#1]
Can you update it for 0.3.7 RC2 ?
http://forum.sa-mp.com/showthread.php?t=559572

**Comment by ikkentim** [comment]
The addresses will change every release candidate. It is pointless to update fcnpc for any RC of SA-MP.

**Comment by m0k1** [comment]
Yea, but my server moved to RC ... And i can't use this plugin anymore ...

**Comment by zeelorenc** [comment]
Structure changed most likely, I probably won't be able to adjust it but I'll see anyway. 

Currently, 0.3.7 is not officially released thus no intention will be to update it yet.

**Comment by m0k1** [comment]
But i need it for RC couse im preparing my script for update ... So i need to test if plugin is working too ...  I don't want to wait last moment for update and moving to 0.3.7; And off topic btw is there any tutorial where i can learn how to dump memory adress for things like this in sa-mp ?

**Comment by zeelorenc** [comment]
1. I don't have intention to do it any time soon, and nothing will change that.

2. Search for youtube tutorials; Fleephacks makes some decent videos about memory hacking (don't know if it'll be relevant tho)
